//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsTester.AddressSearchWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddressSearchWS.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name number from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFullAddress", ReplyAction="*")]
        WsTester.AddressSearchWS.GetFullAddressResponse GetFullAddress(WsTester.AddressSearchWS.GetFullAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFullAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WsTester.AddressSearchWS.GetFullAddressResponse> GetFullAddressAsync(WsTester.AddressSearchWS.GetFullAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullAddress", Namespace="http://tempuri.org/", Order=0)]
        public WsTester.AddressSearchWS.GetFullAddressRequestBody Body;
        
        public GetFullAddressRequest() {
        }
        
        public GetFullAddressRequest(WsTester.AddressSearchWS.GetFullAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFullAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postcode;
        
        public GetFullAddressRequestBody() {
        }
        
        public GetFullAddressRequestBody(string number, string postcode) {
            this.number = number;
            this.postcode = postcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public WsTester.AddressSearchWS.GetFullAddressResponseBody Body;
        
        public GetFullAddressResponse() {
        }
        
        public GetFullAddressResponse(WsTester.AddressSearchWS.GetFullAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFullAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFullAddressResult;
        
        public GetFullAddressResponseBody() {
        }
        
        public GetFullAddressResponseBody(string GetFullAddressResult) {
            this.GetFullAddressResult = GetFullAddressResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WsTester.AddressSearchWS.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WsTester.AddressSearchWS.WebService1Soap>, WsTester.AddressSearchWS.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsTester.AddressSearchWS.GetFullAddressResponse WsTester.AddressSearchWS.WebService1Soap.GetFullAddress(WsTester.AddressSearchWS.GetFullAddressRequest request) {
            return base.Channel.GetFullAddress(request);
        }
        
        public string GetFullAddress(string number, string postcode) {
            WsTester.AddressSearchWS.GetFullAddressRequest inValue = new WsTester.AddressSearchWS.GetFullAddressRequest();
            inValue.Body = new WsTester.AddressSearchWS.GetFullAddressRequestBody();
            inValue.Body.number = number;
            inValue.Body.postcode = postcode;
            WsTester.AddressSearchWS.GetFullAddressResponse retVal = ((WsTester.AddressSearchWS.WebService1Soap)(this)).GetFullAddress(inValue);
            return retVal.Body.GetFullAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsTester.AddressSearchWS.GetFullAddressResponse> WsTester.AddressSearchWS.WebService1Soap.GetFullAddressAsync(WsTester.AddressSearchWS.GetFullAddressRequest request) {
            return base.Channel.GetFullAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsTester.AddressSearchWS.GetFullAddressResponse> GetFullAddressAsync(string number, string postcode) {
            WsTester.AddressSearchWS.GetFullAddressRequest inValue = new WsTester.AddressSearchWS.GetFullAddressRequest();
            inValue.Body = new WsTester.AddressSearchWS.GetFullAddressRequestBody();
            inValue.Body.number = number;
            inValue.Body.postcode = postcode;
            return ((WsTester.AddressSearchWS.WebService1Soap)(this)).GetFullAddressAsync(inValue);
        }
    }
}
